### ISSUE TITLE
ImportError: cannot import name b

### ISSUE THREAD

**Issue by stodge** [jbalogh/tornado-websocket-client#4]
Does this support the current version of Tornado? I'm getting:

./test_websocket.py 
Traceback (most recent call last):
  File "./test_websocket.py", line 3, in <module>
    import websocket
  File "/home/mike/Development/test/websocket.py", line 24, in <module>
    from tornado.util import bytes_type, b
ImportError: cannot import name b

**Comment by a1k0n** [comment]
Yeah, it looks like the following patch is needed to make it work:

```
diff --git a/websocket.py b/websocket.py
index 28e437e..52a5832 100644
--- a/websocket.py
+++ b/websocket.py
@@ -21,7 +21,7 @@ import urlparse
 import tornado.escape
 from tornado import ioloop, iostream
 from tornado.httputil import HTTPHeaders
-from tornado.util import bytes_type, b
+from tornado.util import bytes_type


 # The initial handshake over HTTP.
@@ -127,13 +127,13 @@ class WebSocket(object):
         self._write_frame(True, opcode, message)

     def ping(self):
-        self._write_frame(True, 0x9, b(''))
+        self._write_frame(True, 0x9, b'')

     def close(self):
         """Closes the WebSocket connection."""
         if not self.server_terminated:
             if not self.stream.closed():
-                self._write_frame(True, 0x8, b(""))
+                self._write_frame(True, 0x8, b"")
             self.server_terminated = True
         if self.client_terminated:
             if self._waiting is not None:
```

I'm guessing this thing is unmaintained and ws4py is a better choice these days?
